//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : flower.cpp
//  @ Date : 22.12.2022
//  @ Author : 
//
//


#include "Flower.h"

string Flower::get_name() {
    return flower_name;
}

int Flower::get_quantity() {
    return quantity;
}

float Flower::get_price() {
    return price;
}

void Flower::set_price(float flw_price) {
    price=flw_price;
}

void Flower::set_quantity(int flw_price) {
    price=flw_price;
}

