//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : flower.h
//  @ Date : 19.12.2022
//  @ Author : 
//
//

#include"string"
#if !defined(_FLOWER_H)
#define _FLOWER_H
using namespace std;

class Flower {
private:
    string flower_name;
	int quantity;
    float price;
public:
    string get_name();
    int get_quantity();
    float get_price();
    void set_quantity(int flw_price);
    void set_price(float flw_price);
};

#endif  //_FLOWER_H
