//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : flower.h
//  @ Date : 19.12.2022
//  @ Author : 
//
//

#include"string"
#if !defined(_FLOWER_H)
#define _FLOWER_H
using namespace std;

class Flower {
public:
    string flower_name;
	int quantity;
    float price;
};

#endif  //_FLOWER_H
