//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Order_list.h
//  @ Date : 20.12.2022
//  @ Author : 
//
//


#if !defined(_ORDER_LIST_H)
#define _ORDER_LIST_H
#include "Order.h"
#include<iostream>
using namespace std;


class Order_list {
private:
    list<Order*> order_list;
    list<Order*>::iterator iter;
public:
    ~Order_list();
    void add_order(Order *order);
    void get_order_list_from_file(char* path);
    void put_order_list_to_file(char* path);
    void get_order_list();
    float total_profit();
    float total_cost();

};

#endif  //_ORDER_LIST_H
