//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Order_list.h
//  @ Date : 20.12.2022
//  @ Author : 
//
//
#include "Order.h"

#if !defined(_ORDER_LIST_H)
#define _ORDER_LIST_H


class Order_list {
private:
    list<Order*> Order_list;
    list<Order*>::iterator it_order;
public:
	void add_order();
	void get_order_list();

};

#endif  //_ORDER_LIST_H
