//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Order_list.cpp
//  @ Date : 20.12.2022
//  @ Author : 
//
//


#include "Order_list.h"

void Order_list::add_order() {
}

void Order_list::get_order_list() {
}

