//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Order.cpp
//  @ Date : 19.12.2022
//  @ Author : 
//
//


#include "Order.h"

void Order::remove_flowers_from_storage() {
}

