//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Order.h
//  @ Date : 19.12.2022
//  @ Author : 
//
//
#include <ctime>
#include<list>
#include<Storage.h>
#if !defined(_ORDER_H)
#define _ORDER_H
using namespace std;

class Order {
private:
    Storage* main_storage;
    time_t date;
	int salesman_id;
    bool is_packaged;
    bool need_delivery;
    float final_price;
    Storage shoping_list;
public:
    Order(Storage* ptr_storage):storage(prt_storage)
    {
        /*а чё всмысле?*/
    }
	void remove_flowers_from_storage();
};

#endif  //_ORDER_H
