//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Order.h
//  @ Date : 19.12.2022
//  @ Author : 
//
//
#include <ctime>
#include<list>
#include<Flower.h>
#if !defined(_ORDER_H)
#define _ORDER_H
using namespace std;

class Order {
private:
    time_t date;
	int salesman_id;
    bool is_packaged;
    bool need_delivery;
    float final_price;
    list<Flower*> flower_list;
public:
	void remove_flowers_from_storage();
};

#endif  //_ORDER_H
