//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Owner.cpp
//  @ Date : 19.12.2022
//  @ Author : 
//
//

#include<iostream>
#include "Owner.h"
using namespace std;
void Owner::add_salesman() {
    int id;
    string nm;
    cout<<"Enter ID"<<endl;
    cin>>id;
    cout<<id<<endl;
    cin.ignore(80, '\n');
    cout<<"Enter Name"<<endl;
    cin>>nm;
    cout<<nm<<endl;
    cin.ignore(80, '\n');

}

void Owner::delete_salesman() {
    int id;
    cout<<"Enter ID"<<endl;
    cin>>id;
    cout<<id<<endl;
    cin.ignore(80, '\n');
}

void Owner::interact() {
    while(true){
        cout << "Press 'i' to add new salesman, \n"
        << "press 'd' to delete salesman, \n"
        << "press 's' to see sum up,\n"
        << "press 'q' to quit: \n";
        char ch = cin.get();
        cin.ignore(80, '\n');
        switch(ch){
        case'i':
            add_salesman();
            break;
        case'd':
            delete_salesman();
            break;
        case's':
            break;
        case'q':
            return;
            break;
        default:
            cout<<"wrong button. \n";
            break;

        }
    }
}

