//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Owner.h
//  @ Date : 19.12.2022
//  @ Author : 
//
//


#if !defined(_OWNER_H)
#define _OWNER_H

#include "User.h"

class TOwner : public User {
public:
	void add_salesman();
	void delete_salesman();
	void interact();
};

#endif  //_OWNER_H
