//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Owner.cpp
//  @ Date : 19.12.2022
//  @ Author : 
//
//


#include "Owner.h"

void TOwner::add_salesman() {
}

void TOwner::delete_salesman() {
}

void TOwner::interact() {
}

