//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : program.cpp
//  @ Date : 19.12.2022
//  @ Author : 
//
//


#include "program.h"

void Program::get_flower_list() {
}

void Program::get_report() {
}

void Program::log_in() {
}

