//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : program.cpp
//  @ Date : 19.12.2022
//  @ Author : 
//
//
char* slm_path = "salesman_list.txt";
char* storage_path = "storage.txt";
#include "program.h"

Program::Program(string nm){
    owner= new Owner(&salesman_list , nm);
    salesman_list.get_list_from_file(slm_path);
    storage.get_storage_from_file(storage_path);
}

Program::~Program(){

    salesman_list.put_list_to_file(slm_path);
    storage.put_storage_to_file(storage_path);

}

void Program::get_report() {

}

void Program::get_salesman_list(){
    salesman_list.get_salerman_list();
}

void Program::log_in() {
    int Tempid;
    cout<<"Enter your id"<<endl;
    cin >> Tempid;
    cin.ignore(80, '\n');
    if (Tempid==0){
        autorised_user=owner;
        cout<<"Welcome! "<<autorised_user->get_name()<<endl;
        autorised_user->interact();
    }
   else{
        autorised_user=salesman_list.find_slm(Tempid);
        cout<<"Welcome! "<<autorised_user->get_name()<<endl;
        autorised_user->interact();
    }
}

