//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : program.h
//  @ Date : 19.12.2022
//  @ Author : 
//
//
#include "Flower.h"
#include "Order.h"
#include "Owner.h"
#include "Salesman.h"
#include <list>
#include <vector>



#if !defined(_PROGRAM_H)
#define _PROGRAM_H
using namespace std;

class Program {
private:
    list<Order*> Order_list;
    list<Salesman*> Salesman_list;
    TOwner Owner ;
    vector<Flower*> flower_vect;
    User* autorised_user_id;
public:
	void get_flower_list();
	void get_report();
	void log_in();
};

#endif  //_PROGRAM_H
