//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Salesman.h
//  @ Date : 19.12.2022
//  @ Author : 
//
//


#if !defined(_SALESMAN_H)
#define _SALESMAN_H

#include "User.h"
#include"string"
#include<iostream>
using namespace std;

class Salesman : public User {
public:
    Salesman();
    Salesman(string nm, int sId);
    void add_flower_to_storage();
	void form_order();
	void interact();
};

#endif  //_SALESMAN_H
