//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Salesman.cpp
//  @ Date : 19.12.2022
//  @ Author : 
//
//


#include "Salesman.h"

void Salesman::add_flower_to_storage() {
}

void Salesman::form_order() {
}

void Salesman::interact() {
}

