//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Salesman_list.h
//  @ Date : 20.12.2022
//  @ Author : 
//
//
#include"Salesman.h"
#include<list>
#include<fstream>
#include<sstream>
#include<iostream>
#if !defined(_SALESMAN_LIST_H)
#define _SALESMAN_LIST_H


class Salesman_list {
private:
    list<Salesman*> slm_list;
    list<Salesman*>::iterator iter;
    Storage* storage;
    Order_list* order_list;
public:
    Salesman_list(Storage* st, Order_list* ol):storage(st),order_list(ol){
        /*пусто*/
    }
    ~Salesman_list();
    void add_salerman(Salesman *tmp_slm);
	void get_salerman_list();
    void remove_salesman(int id);
    Salesman* find_slm(int id);
    void put_list_to_file(char* path);
    void get_list_from_file(char *path);
    bool in_list(int id);

};

#endif  //_SALESMAN_LIST_H
