//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Salesman.cpp
//  @ Date : 19.12.2022
//  @ Author : 
//
//
#include "Salesman.h"



Salesman::Salesman(string nm, int sId,Storage* st, Order_list* ol):storage(st),order_list(ol){
    User::name=nm;
    User::id=sId;

}
void Salesman::add_flower_to_storage() {
    string flower_name;
        int count, price;
        cout<<"enter flower name: "<<endl;
        cin>>flower_name;
        cin.ignore(80, '\n');
        cout<<"enter flower count"<<endl;
        cin>>count;
        cin.ignore(80, '\n');
        cout<<"enter each flower price"<<endl;
        cin>>price;
        cin.ignore(80, '\n');
        Flower* ptr_flower= new Flower(flower_name,count,price);
        storage->add_flower(ptr_flower);
        storage->get_flower_list();
}

void Salesman::form_order() {
}

void Salesman::interact() {
    while(true){
        cout << "Press 'i' to add flower to storage, \n"
        << "press 'f' to form order, \n"
        << "press 'q' to quit: \n";
        char ch = cin.get();
        cin.ignore(80, '\n');
        switch(ch){
        case'i':
            add_flower_to_storage();
            break;
        case'f':
            form_order();
            break;
        case'q':
            return;
            break;
        default:
            cout<<"wrong button. \n";
            break;

        }
    }
}

