//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Storage.h
//  @ Date : 20.12.2022
//  @ Author : 
//
//
#include<Flower.h>
#include<vector>
#include<string>
using namespace std;

#if !defined(_STORAGE_H)
#define _STORAGE_H


class Storage {
private:
    vector<Flower*> flower_vect;
    vector<Flower*>::iterator iter;
public:
	void add_flower();
    void get_flower_list(string fl_nm, int quantity, int price);

};

#endif  //_STORAGE_H
