//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Storage.cpp
//  @ Date : 20.12.2022
//  @ Author : 
//
//


#include "Storage.h"

void Storage::add_flower() {
}

void Storage::get_flower_list(string fl_nm, int quantity, int price) {
}

