//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Summary.h
//  @ Date : 22.12.2022
//  @ Author : 
//
//


#if !defined(_SUMMARY_H)
#define _SUMMARY_H


class Summary {
private:
	int order_list;
	int salesman_list;
	int storage;
public:
	void to_sum_up();
};

#endif  //_SUMMARY_H
