//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Summary.cpp
//  @ Date : 22.12.2022
//  @ Author : 
//
//


#include "Summary.h"

void Summary::to_sum_up() {
}

