//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : User.h
//  @ Date : 19.12.2022
//  @ Author : 
//
//

#include"string"
#if !defined(_USER_H)
#define _USER_H
using namespace std;
class User {
private:
    string name;
	int id;
public:
	void get_id();
	void get_name();
};

#endif  //_USER_H
