//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : User.cpp
//  @ Date : 19.12.2022
//  @ Author : 
//
//


#include "User.h"

void User::get_id() {
}

void User::get_name() {
}

