//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : User.cpp
//  @ Date : 19.12.2022
//  @ Author : 
//
//


#include "User.h"

int User::get_id() {
    return id;
}

string User::get_name() {
    return name;
}
void User::set_id(int ID){
    id=ID;
}
void User::set_name(string nm){
    name=nm;
}
